### ISSUE TITLE
define methods to study the time complexity in another class

### ISSUE THREAD

**Issue by misael-diaz** [SantiagoMercado123/Closest-Pair-Problem-Lab-02#1]
https://github.com/SantiagoMercado123/Closest-Pair-Problem-Lab-02/blob/6e4ded655a916250f23f6cd32da958fea2331a13/ClosestPairHalves.java#L24

Do this to improve the organization of your code.

**Comment by SantiagoMercado123** [comment]
Fixed (I think so). Already uploaded it with all the corrections, it works correctly and keeps the O(n) time complexity. Also got rid of some useless lines of code that I forgot to delete before submitting.
