### ISSUE TITLE
the source does not conform to the rubric

### ISSUE THREAD

**Issue by misael-diaz** [SantiagoMercado123/Closest-Pair-Problem-Lab-02#2]
https://github.com/SantiagoMercado123/Closest-Pair-Problem-Lab-02/blob/6e4ded655a916250f23f6cd32da958fea2331a13/ClosestPairHalves.java#L1

Revise your code so that it conforms to the Rubric in every aspect.

**Comment by SantiagoMercado123** [comment]
Done. I'll upload it later.
