### ISSUE TITLE
do not store the point coordinates in global variables

### ISSUE THREAD

**Issue by misael-diaz** [SantiagoMercado123/Closest-Pair-Problem-Lab-02#3]
https://github.com/SantiagoMercado123/Closest-Pair-Problem-Lab-02/blob/6e4ded655a916250f23f6cd32da958fea2331a13/ClosestPairHalves.java#L29

It is a bad idea to store the coordinate data in the global scope of the class, define them inside a function instead.

**Comment by SantiagoMercado123** [comment]
Done. I'll upload it later.
