### ISSUE TITLE
define a Point class to store the x and y coordinates

### ISSUE THREAD

**Issue by misael-diaz** [SantiagoMercado123/Closest-Pair-Problem-Lab-02#5]
https://github.com/SantiagoMercado123/Closest-Pair-Problem-Lab-02/blob/6e4ded655a916250f23f6cd32da958fea2331a13/ClosestPairHalves.java#L29

By defining a Point class you will make your code more readable and relate better to the problem you are solving.

**Comment by SantiagoMercado123** [comment]
Done. I'll uploaded later.
