### ISSUE TITLE
use the sort method of the ArrayList

### ISSUE THREAD

**Issue by misael-diaz** [SantiagoMercado123/Closest-Pair-Problem-Lab-02#6]
https://github.com/SantiagoMercado123/Closest-Pair-Problem-Lab-02/blob/6e4ded655a916250f23f6cd32da958fea2331a13/ClosestPairHalves.java#L186

Instead of implementing a (inefficient) sorting algorithm for the linked-list you should change your data structure to an ArrayList and use its sorting method. You will be able to do that if you define a Point class and define a comparator.

**Comment by SantiagoMercado123** [comment]
Just checked it. The function is never used, I was using the ArrayList sorting method (lines 251 and 252). I forgot to delete this function.
